/**
 * AIInsights component provides AI-powered analysis and chat features for electricity usage data.
 *
 * - Displays insights generated by Google Gemini AI based on user's electricity readings.
 * - Allows users to chat with the AI assistant for personalized advice and tips.
 * - Handles configuration errors (e.g., missing API key) and guides users through setup.
 * - Supports refreshing insights and displays loading states.
 * - Uses custom UI components and integrates with the `ai/react` SDK for chat functionality.
 *
 * @component
 * @param {Object} props - Component props.
 * @param {boolean} props.hasData - Indicates if there is electricity data available for analysis.
 * @returns {JSX.Element} The rendered AIInsights component.
 *
 * @example
 * <AIInsights hasData={true} />
 */

import { TabsContent } from "@radix-ui/react-tabs";
import { BarChart3 } from "lucide-react";
import React from "react";
import {
    Card,
    CardHeader,
    CardTitle,
    CardDescription,
    CardContent,
} from "../ui/card";
import UsageChart from "../usage-chart";
import { ElectricityReading } from "@/lib/types";

interface AnalyticsProps {
    readings: ElectricityReading[];
}

function AnalyticsTabs({ readings }: Readonly<AnalyticsProps>) {
    return (
        <TabsContent value="analytics" className="mt-0 space-y-6">
            <Card className="shadow-lg">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <BarChart3 className="h-5 w-5 text-blue-500" />
                        Usage Analytics
                    </CardTitle>
                    <CardDescription>
                        Detailed visualization of your electricity consumption
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <UsageChart readings={readings} />
                </CardContent>
            </Card>
        </TabsContent>
    );
}

export default AnalyticsTabs;
